behaviors:

  FightAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 5000000000
    time_horizon: 128
    summary_freq: 10000
    threaded: true
    self_play:
      window: 30
      play_against_latest_model_ratio: 0.5
      save_steps: 100000
      swap_steps: 100000
      team_change: 500000

#behaviors:
#  FightAgent:
#    trainer_type: ppo
#    hyperparameters:
#      batch_size: 2048
#      buffer_size: 20480
#      learning_rate: 0.003
#      beta: 0.003
#      epsilon: 0.15
#      lambd: 0.93
#      num_epoch: 5
#      learning_rate_schedule: constant
#    network_settings:
#      normalize: false
#      hidden_units: 256
#      num_layers: 3
#      vis_encode_type: simple
#    reward_signals:
#      extrinsic:
#        gamma: 0.99
#        strength: 1.0
#    keep_checkpoints: 5
#    max_steps: 8000000000
#    time_horizon: 1000
#    summary_freq: 20000
#    self_play:
#      window: 30
#      play_against_latest_model_ratio: 0.5
#      save_steps: 100000
#      swap_steps: 100000
#      team_change: 500000
